# platform :ios, '9.0'

target 'ShareImage' do
  use_frameworks!

pod 'Moya/ReactiveSwift', '~> 14.0'

pod 'SDWebImageSwiftUI'


  target 'ShareImageTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Moya/ReactiveSwift', '~> 14.0'
    pod 'SDWebImageSwiftUI'
  end

  target 'ShareImageUITests' do
    # Pods for testing
  end

end
